---
# vars file for vpc
  aws_access_key: "AKIA6AJCEQYZBPDRRP55"
  aws_secret_key: "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"
  vpc_title: "k8s cluster"
  vpcCidrBlock: '10.0.0.0/16'
  subNetCidrBlock: '10.0.1.0/24'
  portCidrBlock: '0.0.0.0/0'
  destinationCidrBlock: '0.0.0.0/0'
  state: "present"
  zone: "ap-south-1b"
  region: "ap-south-1"
